### PR TITLE
Fix bug with timing of configuration version status

### LINKED ISSUE #20: Invalid Attribute error
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### terraform-k8s & Kubernetes Version

operator: 0.1.1-alpha
k8s: `Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}`

### Affected Resource(s)

workspace

### Terraform Configuration Files

```hcl
terraform {
  backend "remote" {
    organization = "workarea-commerce"
    workspaces
    {
      name = "egdod-staging-tf-egdod-staging-helios"
    }
  }
}
variable "cluster_name" {}
variable "recaptcha_api_key" {}
variable "recaptcha_secret" {}

module "operator" {
  source = "app.terraform.io/workarea-commerce/helios/aws"
  version = "1.0.6"
  cluster_name = var.cluster_name
  recaptcha_api_key = var.recaptcha_api_key
  recaptcha_secret = var.recaptcha_secret
}
```

### Debug Output

https://gist.github.com/mcfearsome/21990e1580f3413f8eec954ad61c4f16

### Expected Behavior

I expect the workspace to get planned/applied

### Actual Behavior

Throwing `Invalid Attribute` error. 

This run was only a version bump, with no changes to the inputs or their values.

### Steps to Reproduce

This is happening intermittently, I do not have a concrete set of steps. Sometimes it will throw this and I will still see the plan/apply in TF cloud, others it just stops and never tries again.

It would be helpful if the error output included what attribute it is having trouble with at the very least. It also seems like the status on the workspace doesn't get properly updated when this happens as it is currently `applied` in my cluster.

### Important Factoids

I have customized the helm chart to allow for workspace resources to be in any namespace

### PR DESCRIPTION
**Pull request by mcfearsome**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #20 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-k8s/blob/master/CHANGELOG.md):

```release-note
* Fix bug where the configuration version in TFC isn't in an "uploaded" status when the run is started
```

### CODE REVIEW

**Comment by mcfearsome** [comment]
I left out my changes to `CreateRun` as it doesn't seem to be in use.

File: pkg/controller/workspace/tfc_run.go [hunk 1]
```diff
@@ -29,6 +29,24 @@ func (t *TerraformCloudClient) UploadConfigurationFile(uploadURL string) error {
 	return nil
 }
 
+// WaitForConfigurationUploaded waits a small amount of time for the configuration version to be "uploaded"
+func (t *TerraformCloudClient) WaitForConfigurationUploaded(id string) error {
```
Comment (koikonom) [inline pkg/controller/workspace/tfc_run.go:33]: I wanted to solve a similar problem for VCS backed workspaces and I was told at the time it's better to avoid blocking in the reconcile function and just retry instead. See https://github.com/hashicorp/terraform-k8s/pull/70#discussion_r498518775 for more context.

As a result I changed my method to return a bool if we need to requeue (and retry) of if we were able to start the job. See https://github.com/hashicorp/terraform-k8s/blob/80bf499e93541db07e780b55ecdb955e6ea5b797/pkg/controller/workspace/workspace_controller.go#L403-L407 and 
https://github.com/hashicorp/terraform-k8s/blob/80bf499e93541db07e780b55ecdb955e6ea5b797/pkg/controller/workspace/workspace_controller.go#L374-L390 .


That said and while I'm typing these words I realise that the only thing `prepareVcsRun` does is to check if there is a state available or not. Since we need this check for both cases (VCS or module based) a possible solution would be to rename `prepareVcsRun` to `checkForConfigVersion` and change the if block from this:
```
	var err error
	requeue := false
	if instance.Spec.VCS != nil {
		requeue, err = r.prepareVCSRun(instance)
	} else if instance.Spec.Module != nil {
		err = r.prepareModuleRun(instance, options)
	}
	if err != nil {
		return err
	} else if requeue {
		// When requeue is true it means that the workspace is not ready yet.
		return nil
	}
```

to this: 
```
	if instance.Spec.Module != nil {
		if err := r.prepareModuleRun(instance, options); err != nil {
                        return err
                }
	}

        requeue, err = r.checkForConfigVersion(instance)
	if err != nil {
		return err
	} else if requeue {
		// When requeue is true it means that the workspace is not ready yet.
                // Since we are returning before setting a RunID the reconcile method will 
                // retry this part of the code.
		return nil
	}

```

(I wrote the code in the PR editor, there are probably a few typos here and there :) ) .

You may want to enhance `checkForConfig` (currently named `prepareVcsRun`) to optionally look for a specific state ID instead of just checking if there is a state uploaded or not.

**Review by koikonom — CHANGES_REQUESTED** [review]
Hello @mcfearsome!

Thank you for taking the time to submit this PR. I think there is one thing that we should change before merging this. I've left a comment, take a look and let me know what you think.

If you don't have time to make the change yourself just let me know and I'll take care of it, once I complete a couple other operator-related tasks I have on my plate.

**Comment by mcfearsome** [comment]
Thank you @koikonom for the review! Your suggestions make sense, using a sleep is generally something I try to avoid in any language but I took your code as permission to do so 😁 not to mention the added complication and the fact I was focused on getting a working operator for other work I was trying to complete (this operator is on its way to becoming a core part of our infra and I just put it into a production cluster for the first time 😬). I believe I will have to store the configuration version in the status now so that I can check the status before uploaded. I should be able to rework this over the next day or so.

**Comment by mcfearsome** [comment]
Thinking through this a little more I'm trying to determine how to know when I need to upload a new config version. It seems to me that I would have to pull down the actual uploaded config (a quick read of the api docs doesn't appear to show a clear way of getting this) so I can compare, or possibly using an intermediary state in the status to let me know the config has been uploaded but not run. Forgive me if I'm missing something obvious, I'm on mobile and haven't had a chance to really read through everything yet.

**Comment by koikonom** [comment]
Yeah that function should have been removed when I moved things around, but I missed it :) Sorry for that.

As for your other question, here are a few suggestions:

* The next version of the operator will support VCS backed workspaces. Instead of passing a module to the workspace CR you will be able to pass a repository. The operator will then create the workspace, connect it to the VCS repository, and start a run. If a change is pushed to the main branch of the repository TFC will automatically start a new run. In the mean time the operator wakes up every few minutes and checks if there has been a new run and if there has been one it pulls the latest outputs from it.

* If your use case works better with modules instead of VCS repos then you could either [pass a git reference to the module URL](https://www.terraform.io/docs/modules/sources.html#selecting-a-revision) or change the module version. Both things will result in the terraform template being updated, which triggers the creation of a new Configuration Version.

Hope these help.

**Comment by koikonom** [comment]
You only need to upload a new Configuration Version if you trigger a new run, and the only way to trigger a new run is to either change the module version, or if someone changes the variables on the workspace.

**Comment by mcfearsome** [comment]
I have re-worked this to utilize the built-in Requeue mechanism and even included a test! I am still new to Golang and this is the first real test I've written I think so please let me know if there are things I could do better.

File: deploy/crds/app.terraform.io_workspaces_crd.yaml [hunk 2]
```diff
@@ -1,4 +1,4 @@
-apiVersion: apiextensions.k8s.io/v1
+apiVersion: apiextensions.k8s.io/v1beta1
```
Comment (mcfearsome) [inline deploy/crds/app.terraform.io_workspaces_crd.yaml:1]: `apiextensions.k8s.io/v1` would require k8s 1.16.0+. As a reference the current lowest version of EKS is 1.14 with an "end of support" date of December 8, 2020. Then 1.15 is supported until May, 2021. Might be best to stay on v1beta1 as it will be supported until 1.19.

File: pkg/controller/workspace/tfc_org.go [hunk 3]
```diff
@@ -20,9 +20,21 @@ var (
 	AutoApply = true
 )
 
+type ClientProvider interface {
```
Comment (mcfearsome) [inline pkg/controller/workspace/tfc_org.go:23]: This is a bit convoluted I feel but it was the only way I could think of to be able to mock the tfclient. I'd be happy to be shown a better way.

File: README.md [hunk 4]
```diff
@@ -1,6 +1,6 @@
 # Terraform Cloud Operator for Kubernetes
 
-> This repository contains experimental software which is still under development and in the alpha testing stage. It is not ready for production use.
```
Comment (mcfearsome) [inline README.md:3]: Not sure how these changes came in with mine. I updated my branch with my upstream master to pull in recent changes and then I did a squash & rebase on my commits to clean them up. I can recreate my branch without these if needed.

**Comment by koikonom** [comment]
Hi @mcfearsome, thanks for working on this. Sorry I haven't responded to it yet, but it's definitely on my to-do list.

**Review by koikonom — CHANGES_REQUESTED** [review]
Hey @mcfearsome, again sorry for the long delay. The PR looks great overall, just a potential gotcha I spotted and a request to rebase against latest master :) .

File: pkg/controller/workspace/workspace_controller.go [hunk 5]
```diff
@@ -337,38 +338,69 @@ func (r *ReconcileWorkspace) updateVariables(instance *appv1alpha1.Workspace) (b
...
+			return true, err
+		}
+
+		instance.Status.ConfigVersionID = configVersion.ID
+		if err = r.client.Status().Update(context.TODO(), instance); err != nil {
+			r.reqLogger.Error(err, "Failed to update Workspace status")
+			return true, err
+		}
+	} else {
+		configVersion, err = r.tfclient.Client.ConfigurationVersions.Read(context.TODO(), instance.Status.ConfigVersionID)
```
[the remark this answers is not in the document]
Comment (mcfearsome) [reply pkg/controller/workspace/workspace_controller.go:383]: Makes sense, won't be hard to move this around.

**Review by koikonom — APPROVED** [review]
Thank you very much for doing this!
